dubbo:
  application:
    id: xmall-front
    name: xmall-front
  registry:
    address: zookeeper://192.168.31.234:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20880
  consumer:
    version: 1.0.1
    group: xmall
xmall:
  rateLimit:
    enable: true
    timeout: 1000
    limit: 20
  redis:
    host: 192.168.31.234
    port: 6379
spring:
  application:
    name: xmall-front-web
  session:
    store-type: redis
  redis:
    host: 192.168.31.234
    port: 6379