# Single Dubbo Config Bindings
## ApplicationConfig
dubbo:
  application:
    id: xmallService
    name: xmallService
  ## ModuleConfig
  module:
    id: moduleBean
    name: dubbo-demo-module

  ## RegistryConfig
  registry:
    address: zookeeper://47.74.235.50:2181
  ## ProtocolConfig
  protocol:
    name: dubbo
    port: 20880
  consumer:
    version: 1.0.1
    group: xmall
redis:
  host: 47.74.235.50
  port: 6379
aliyun:
  oss:
    accessKeyId: LTAIcklXsm0lpGak
    accessKeySecret: XsFwUNziSWH1tqnER5j7fAXK3WZbkf
    imgBuckName: xmall-img
    imgBuckOrigin: https://xmall-img.oss-cn-beijing.aliyuncs.com/
    endPoint: oss-cn-beijing.aliyuncs.com
mall:
  corsDomainPattern: ^(http|https)://.*$